# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Apprendendo PHP
email: profmilla@apprendendo.blog
description: >- # this means to ignore newlines until "baseurl:"
  Apprendendo PHP é um blog dedicado a compartilhar conhecimento sobre a linguagem de programação PHP, com tutoriais, dicas e projetos práticos para iniciantes e desenvolvedores experientes.
author: Milla
baseurl: "/2InfoApprendendo.github.io" # ou o nome do seu repositório # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: awesome-jekyll-theme #tema Ruby Gem
# remote-theme: "a-chacon/awesome-jekyll-theme" # remote theme for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Polyglot configuration
##
languages: ["pt-BR", "en", "es"]
default_lang: "pt-BR"
active_lang: "pt-BR"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"

# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  # email: "example@example.cl"
  github: "https://github.com/2InfoApprendendo"
  # telegram: "https://t.me/"
  # stackoverflow: "https://stackoverflow.com"
  # discord: "https://discord.com/"
  # mastodon: "https://lile.cl/"
  # threads: "https://www.threads.net/@example"
  # linkedin: "https://www.linkedin.com/in/example/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
